### ISSUE TITLE
The "weak" part?

### ISSUE THREAD

**Issue by Alaneor** [medikoo/es6-weak-map#10]
The native WeakMaps do not have strong references to objects stored in them, which means that the objects can be garbage-collected if there are no more references to them outside of the WeakMap.

How is that handled in this library? Looking at the code, it seems the objects are just stored under a random key. This means that extensive use of this polyfill **will** lead to memory leaks.

Perhaps it could be mentioned in the README?

**Comment by phated** [comment]
WeakMaps are impossible to shim in JS.  Any research would lead to that understanding and this module is also tagged as a ponyfill, not polyfill.

**Comment by medikoo** [comment]
> How is that handled in this library? Looking at the code, it seems the objects are just stored under a random key. This means that extensive use of this polyfill will lead to memory leaks.

@Alaneor This implementation works by storing a _string id_ of a weak map on a hidden property of an object which is _added_ to map. There are no references to added objects kept, therefore they're not blocked from being garbage collected.
