### ISSUE TITLE
Add prettier config to package.json

### ISSUE THREAD

**Issue by dan-lee** [medikoo/es6-weak-map#12]
Can you add your prettier config to `package.json` or `.prettierrc`? This makes it easier for contributions as I've got my personal `~/.prettierrc` with different styles.

**Comment by medikoo** [comment]
Thanks for request, it was already on a _to do_ list, added with d4448b88675468732303e3f521bf232700b23feb & abaecd2de22e66bbe431b8837f2a5a2e4c3d6e7a
