### ISSUE TITLE
Destructive API changes with PATCH version

### ISSUE THREAD

**Issue by AlexKVal** [medikoo/es6-weak-map#5]
Here is the problem: https://github.com/karma-runner/karma/issues/1372

It seems `es6-weak-map` project needs to change MAJOR number in version,
because of destructive API changes.

**Comment by AlexKVal** [comment]
I'm closing this because of https://github.com/karma-runner/karma/issues/1372#issuecomment-92247354

**Comment by medikoo** [comment]
This issue is valid, it should have been a major. I've published v0.1.4 which brings back v0.1.2. and what was published as v0.1.3 will be published as v1.0.0

**Comment by AlexKVal** [comment]
Thank you!
