### ISSUE TITLE
Looks like a ponyfill

### ISSUE THREAD

**Issue by tomekwi** [medikoo/es6-weak-map#7]
The term *ponyfill* is supposed to mean “A polyfill that doesn't overwrite the native method”. I guess it was crafted by @sindresorhus – at least [he uses it extensively](https://github.com/sindresorhus/object-assign/blob/e7f515d/readme.md). It seems to have [caught on](https://www.npmjs.com/browse/keyword/ponyfill).

Anyway, your lib looks like it’s one of those. You might want to mention that as a tag or something – I couldn’t find it here: <http://npmsearch.com/?q=map%20AND%20ponyfill>.

**Comment by sindresorhus** [comment]
:+1:

**Comment by medikoo** [comment]
Thanks! Published with v1.0.2

**Comment by tomekwi** [comment]
:+1:
